### PR TITLE
Send mail order to user

### PR DESCRIPTION
**Pull request by VanHoa18042000**
## Related Tickets
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/51518)

## WHAT (optional)
- send_mail_notification_order_to_user

## HOW
- Add css, js for home page , admin , layout login . And add gem i18n

## WHY (optional)
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.

### CODE REVIEW

**Comment by VanHoa18042000** [comment]
ready

**Comment by manhnt-0960** [comment]
commented
commits

**Comment by VanHoa18042000** [comment]
ready

**Review by anlvq-1058 — COMMENTED** [review]
merged

**Pull request merged**
