### PR TITLE
template category

### PR DESCRIPTION
**Pull request by caovanson06112001**
## Related Tickets
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/51440)

## WHAT (optional)
- Add theme for category , add sweetalet.js , show category books

## HOW
- Add theme for category , add sweetalet.js , show category books

## WHY (optional)
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.

## Evidence (Screenshot or Video)

Screenshot from 2022-08-04 17-19-03

### CODE REVIEW

**Comment by caovanson06112001** [comment]
ready

**Comment by manhnt-0960** [comment]
gắn hình sản phẩm, chứ gắn hình code làm gì e ?

**Comment by manhnt-0960** [comment]
commented

**Comment by caovanson06112001** [comment]
image

**Comment by caovanson06112001** [comment]
ready

**Pull request merged**
